clone:
  depth: full

pipelines:
  default:
  - parallel:
    - step:
        name: 'Node 6.x'
        image: node:6.17.0
        script:
        - ./bin/build.sh
    - step:
        name: 'Node 8.x'
        image: node:8.15.1
        script:
        - ./bin/build.sh
    - step:
        name: 'Node 10.x'
        image: node:10.15.2
        script:
        - ./bin/build.sh
  - step:
      name: 'Node 11.x'
      image: node:11.10.1
      script:
      - ./bin/build.sh
